const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('firefly', {
  chooseMusicFiles: () => ipcRenderer.invoke('library:choose-files'),
  chooseMusicFolder: () => ipcRenderer.invoke('library:choose-folder'),
  addLiveFolder: () => ipcRenderer.invoke('library:add-live-folder'),
  syncLiveFolders: folders => ipcRenderer.invoke('library:sync-live-folders', folders),
  rescanLiveFolder: folder => ipcRenderer.invoke('library:rescan-live-folder', folder),
  removeLiveFolder: id => ipcRenderer.invoke('library:remove-live-folder', id),
  onLiveFolderSnapshot: callback => { const listener = (_event, snapshot) => callback(snapshot); ipcRenderer.on('library:live-folder-snapshot', listener); return () => ipcRenderer.removeListener('library:live-folder-snapshot', listener); },
  chooseMusicZip: () => ipcRenderer.invoke('library:choose-zip'),
  loadState: () => ipcRenderer.invoke('state:load'),
  saveState: state => ipcRenderer.invoke('state:save', state),
  loadCredentials: () => ipcRenderer.invoke('credentials:load'),
  saveCredentials: credentials => ipcRenderer.invoke('credentials:save', credentials),
  openDataDirectory: () => ipcRenderer.invoke('state:open-directory'),
  ensureDynamicFonts: () => ipcRenderer.invoke('dynamic-case:ensure-fonts'),
  generateDynamicCaseArt: options => ipcRenderer.invoke('dynamic-case:generate', options),
  searchArtistImages: (artist, options) => ipcRenderer.invoke('artist:image-search', artist, options),
  cacheArtistImage: options => ipcRenderer.invoke('artist:image-cache', options),
  searchYouTubeVideos: options => ipcRenderer.invoke('video:search-youtube', options),
  lookupLyrics: options => ipcRenderer.invoke('lyrics:lookup', options),
  testSunoConnection: () => ipcRenderer.invoke('suno:test'),
  createSunoTask: options => ipcRenderer.invoke('suno:create', options),
  querySunoTask: taskId => ipcRenderer.invoke('suno:query', taskId),
  importSunoTrack: options => ipcRenderer.invoke('suno:import-track', options),
  checkForUpdates: channel => ipcRenderer.invoke('update:check', channel),
  downloadUpdate: channel => ipcRenderer.invoke('update:download', channel),
  launchUpdate: () => ipcRenderer.invoke('update:launch'),
  onUpdateProgress: callback => { const listener = (_event, progress) => callback(progress); ipcRenderer.on('update:progress', listener); return () => ipcRenderer.removeListener('update:progress', listener); },
  onUpdateReady: callback => { const listener = (_event, update) => callback(update); ipcRenderer.on('update:ready', listener); return () => ipcRenderer.removeListener('update:ready', listener); },
  platform: process.platform
});
