const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('firefly', {
  signalAppReady: () => ipcRenderer.send('app:renderer-ready'),
  chooseMusicFiles: () => ipcRenderer.invoke('library:choose-files'),
  chooseMusicFolder: () => ipcRenderer.invoke('library:choose-folder'),
  addLiveFolder: () => ipcRenderer.invoke('library:add-live-folder'),
  syncLiveFolders: folders => ipcRenderer.invoke('library:sync-live-folders', folders),
  rescanLiveFolder: folder => ipcRenderer.invoke('library:rescan-live-folder', folder),
  removeLiveFolder: id => ipcRenderer.invoke('library:remove-live-folder', id),
  onLiveFolderSnapshot: callback => { const listener = (_event, snapshot) => callback(snapshot); ipcRenderer.on('library:live-folder-snapshot', listener); return () => ipcRenderer.removeListener('library:live-folder-snapshot', listener); },
  setPlaybackState: state => ipcRenderer.send('media:playback-state', state),
  onMediaCommand: callback => { const listener = (_event, command) => callback(command); ipcRenderer.on('media:command', listener); return () => ipcRenderer.removeListener('media:command', listener); },
  configureDiscordPresence: config => ipcRenderer.invoke('discord:configure', config),
  onDiscordStatus: callback => { const listener = (_event, status) => callback(status); ipcRenderer.on('discord:status', listener); return () => ipcRenderer.removeListener('discord:status', listener); },
  getAccountStatus: () => ipcRenderer.invoke('account:status'),
  openAccountPortal: options => ipcRenderer.invoke('account:open', options),
  claimAccountCode: options => ipcRenderer.invoke('account:claim', options),
  signOutAccount: () => ipcRenderer.invoke('account:sign-out'),
  syncAccountNow: state => ipcRenderer.invoke('account:sync-now', state),
  syncRepairedTrack: state => ipcRenderer.invoke('account:repair-track-sync', state),
  restoreAccountCloud: () => ipcRenderer.invoke('account:restore'),
  downloadCloudTracks: (tracks, options) => ipcRenderer.invoke('account:download-tracks', tracks, options),
  removeCloudDownloads: tracks => ipcRenderer.invoke('account:remove-downloads', tracks),
  repairTrackFile: track => ipcRenderer.invoke('library:repair-track', track),
  onAccountSyncStatus: callback => { const listener = (_event, status) => callback(status); ipcRenderer.on('account:sync-status', listener); return () => ipcRenderer.removeListener('account:sync-status', listener); },
  chooseMusicZip: () => ipcRenderer.invoke('library:choose-zip'),
  loadState: () => ipcRenderer.invoke('state:load'),
  saveState: state => ipcRenderer.invoke('state:save', state),
  loadCredentials: () => ipcRenderer.invoke('credentials:load'),
  saveCredentials: credentials => ipcRenderer.invoke('credentials:save', credentials),
  openDataDirectory: () => ipcRenderer.invoke('state:open-directory'),
  ensureDynamicFonts: () => ipcRenderer.invoke('dynamic-case:ensure-fonts'),
  generateDynamicCaseArt: options => ipcRenderer.invoke('dynamic-case:generate', options),
  searchArtistImages: (artist, options) => ipcRenderer.invoke('artist:image-search', artist, options),
  cacheArtistImage: options => ipcRenderer.invoke('artist:image-cache', options),
  searchYouTubeVideos: options => ipcRenderer.invoke('video:search-youtube', options),
  lookupLyrics: options => ipcRenderer.invoke('lyrics:lookup', options),
  testSunoConnection: () => ipcRenderer.invoke('suno:test'),
  createSunoTask: options => ipcRenderer.invoke('suno:create', options),
  querySunoTask: taskId => ipcRenderer.invoke('suno:query', taskId),
  importSunoTrack: options => ipcRenderer.invoke('suno:import-track', options),
  checkForUpdates: channel => ipcRenderer.invoke('update:check', channel),
  getCurrentRelease: () => ipcRenderer.invoke('update:current-release'),
  downloadUpdate: channel => ipcRenderer.invoke('update:download', channel),
  launchUpdate: () => ipcRenderer.invoke('update:launch'),
  onUpdateProgress: callback => { const listener = (_event, progress) => callback(progress); ipcRenderer.on('update:progress', listener); return () => ipcRenderer.removeListener('update:progress', listener); },
  onUpdateReady: callback => { const listener = (_event, update) => callback(update); ipcRenderer.on('update:ready', listener); return () => ipcRenderer.removeListener('update:ready', listener); },
  platform: process.platform
});
